export const ROOM_CREATE_INIT = 'ROOM_CREATE_INIT';
export const ROOM_CREATE_FAIL = 'ROOM_CREATE_FAIL';
export const ROOM_CREATE_SUCCESS = 'ROOM_CREATE_SUCCESS';

export const FETCH_ROOMS_INIT = 'FETCH_ROOMS_INIT';
export const FETCH_ROOMS_FAIL = 'FETCH_ROOMS_FAIL';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';

export const SEND_MESSAGE_INIT = 'SEND_MESSAGE_INIT';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';

export const FETCH_MESSAGES_INIT = 'FETCH_MESSAGES_INIT';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';

export const AUTH_USER_CREATE_INIT = 'AUTH_USER_CREATE_INIT';
export const AUTH_USER_CREATE_FAIL = 'AUTH_USER_CREATE_FAIL';
export const AUTH_USER_CREATE_SUCCESS = 'AUTH_USER_CREATE_SUCCESS';

export const AUTH_CHANGE_PASSWORD_INIT = 'AUTH_CHANGE_PASSWORD_INIT';
export const AUTH_CHANGE_PASSWORD_FAIL = 'AUTH_CHANGE_PASSWORD_FAIL';
export const AUTH_CHANGE_PASSWORD_SUCCESS = 'AUTH_CHANGE_PASSWORD_SUCCESS';

export const AUTH_LOGOUT_INIT = 'AUTH_LOGOUT_INIT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

export const AUTH_USER_LOGIN_INIT = 'AUTH_USER_LOGIN_INIT';
export const AUTH_USER_LOGIN_FAIL = 'AUTH_USER_LOGIN_FAIL';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';

export const AUTH_USER_INIT = 'AUTH_USER_INIT';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
