export const LOGIN_USER = 'LOGIN_USER';
export const USER_START_LOGIN = 'USER_START_LOGIN';
export const USER_FINISH_LOGIN = 'USER_FINISH_LOGIN';

export const START_FETCHING_MESSAGES = 'START_FETCHING_MESSAGES';
export const MESSAGES_FETCHED = 'MESSAGES_FETCHED';
export const ADD_MESSAGE = 'ADD_MESSAGE';
